service: lambda-appsync-boilerplate

frameworkVersion: '3'

provider:
  name: aws # name of the provider
  runtime: nodejs20.x
  stage: ${opt:stage,'local'}
  region: ap-south-1
  profile: nm_personal_aws # aws profile name which we have in .aws folder
  timeout: 900
  versionFunctions: false
  environment:
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'
    - Effect: Allow
      Action:
        - 'ec2:DescribeNetworkInterfaces'
        - 'ec2:CreateNetworkInterface'
        - 'ec2:DeleteNetworkInterface'
        - 'ec2:DescribeInstances'
        - 'ec2:AttachNetworkInterface'
      Resource:
        - '*'

plugins:
  - serverless-appsync-plugin
  - serverless-appsync-simulator
  - serverless-offline
  - serverless-webpack
  - serverless-prune-plugin

custom:
  serviceName: ${self:service}
  prune:
    includeLayers: true
    automatic: true
    number: 3
  serverless-offline:
    httpPort: 4000
  accountId: 837226227340 # aws account id
  appsync-emulator:
    buildPrefix: .webpack/service
  appsync-simulator:
    apiKey: da2-fakeApiId123456
    location: '.webpack/service'
    port: 3000
    schema: schema.graphql

  appSync:
    name: ${self:custom.serviceName}-${sls:stage}
    authenticationType: API_KEY
    # authenticationType: AMAZON_COGNITO_USER_POOLS
    # additionalAuthenticationProviders:
    #   - authenticationType: API_KEY

    userPoolConfig:
      awsRegion: # defaults to provider region
      defaultAction: # required # ALLOW or DENY
      userPoolId: # required # user pool ID
      appIdClientRegex: # optional

    schema:
      - src/functions/index.graphql
      - ${file(src/functions/auth/auth.yml):schema}

    mappingTemplates:
      # Query mapping templates
      - ${file(src/functions/auth/auth.yml):mappingTemplates}

    serviceRole: '${aws:region}-${sls:stage}-${self:custom.serviceName}'
    dataSources:
      - ${file(src/functions/auth/auth.yml):dataSources}

package:
  individually: true

functions:
  - ${file(src/functions/auth/auth.yml):functions}

resources:
  Resources:
    appsynclambdaboilerplate:
      Type: 'AWS::IAM::Role'
      Properties:
        RoleName: '${aws:region}-${sls:stage}-${self:custom.serviceName}'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Service:
                  - 'appsync.amazonaws.com'
              Action:
                - 'sts:AssumeRole'
        Policies:
          - PolicyName: '${aws:region}-${sls:stage}-${self:custom.serviceName}-policy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 'lambda:InvokeFunction'
                  Resource: '*'
